# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy the entire repository as it is a monorepo
COPY . .

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Build all workspaces
RUN npm run build --workspaces

EXPOSE 8080

CMD ["node", "src/brave-search/dist/index.js"]
